In [2]:
import torch
print(torch.__version__)

2.3.1+cpu


In [3]:
torch.get_default_dtype()

torch.float32

In [4]:
torch.set_default_dtype(torch.float16)

In [5]:
myTens = torch.Tensor([[1,2,3,4]])


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "e:\A Civil Engineering graduate\Research\ANN\Beginer\venv_ANN_beginer\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "e:\A Civil Engineering graduate\Research\ANN\Beginer\venv_ANN_beginer\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "e:\A Civil Engineering graduate\Research\ANN\Beginer\venv_ANN_begine

In [6]:
torch.numel(myTens)

4

In [7]:
torch.Tensor(4,5)

tensor([[6.6757e-06, 1.5268e-03, 7.5936e-05, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [8]:
intTensor = torch.tensor([3,2]).type(torch.IntTensor)
print(intTensor)

tensor([3, 2], dtype=torch.int32)


In [9]:
torch.cuda.is_available()

False

In [14]:
tensor1 = torch.Tensor([
    [1,2,3],
    [3,4,5]
])
tensor2 = torch.Tensor([
    [5,6,7],
    [7,8,9]
])

In [16]:
print(tensor1.requires_grad)
print(tensor2.requires_grad)

True
True


In [15]:
tensor1.requires_grad_()
tensor2.requires_grad_()

tensor([[5., 6., 7.],
        [7., 8., 9.]], requires_grad=True)

In [17]:
print(tensor1.grad)

None


In [19]:
print(tensor1.grad_fn)

None


In [20]:
output_tensor = tensor1*tensor2

In [21]:
print(output_tensor.grad)

None


C:\Users\Acer\AppData\Local\Temp\ipykernel_16736\1906321212.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten\src\ATen/core/TensorBody.h:494.)
  print(output_tensor.grad)


In [22]:
print(output_tensor.grad_fn)

In [25]:
output_tensor = (tensor1*tensor2).mean()

In [27]:
print(output_tensor.grad_fn)

In [30]:
print(tensor1.grad)
output_tensor.backward()
print(tensor1.grad)

None
tensor([[0.8330, 1.0000, 1.1660],
        [1.1660, 1.3330, 1.5000]])
